# Site settings
title:       Nick McDonnough
email:       nickmcd@gmail.com
author:      Nick McDonnough
description: "A place to put my thoughts."
baseurl:     ""
url:         "http://nickmcd.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:   "nickmcdonnough"
stackoverflow_id:
twitter_username:  "nickmcdonnough"
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
